name = "auth-worker"
main = "src/index.ts"
compatibility_date = "2024-02-23"

[env.production]
name = "auth-worker"

[env.production.vars]
DENTITY_BASE_ENDPOINT = "https://oidc.dentity.com"
APP_REDIRECT = "https://dentity-integration-producti.ens-app-v3.pages.dev"

[env.staging]
name = "auth-worker-staging"

[env.staging.vars]
DENTITY_BASE_ENDPOINT = "https://oidc.staging.dentity.com"
APP_REDIRECT = "https://dentity-integration.ens-app-v3.pages.dev"
